### ISSUE TITLE
paramiko has problem with python3

### ISSUE THREAD

**Issue by martinzellner** [gitsimon/tq_website#47]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/webapps/tq_website/tq_website/tasks.py", line 32, in get_fds_files
    fds_connector = FDSConnection()
  File "/webapps/tq_website/payment/postfinance_connector.py", line 13, in __init__
    self.client.load_host_keys(settings.FDS_HOST_KEY)
  File "/usr/local/lib/python3.4/dist-packages/paramiko/client.py", line 124, in load_host_keys
    self._host_keys.load(filename)
  File "/usr/local/lib/python3.4/dist-packages/paramiko/hostkeys.py", line 101, in load
    e = HostKeyEntry.from_line(line, lineno)
  File "/usr/local/lib/python3.4/dist-packages/paramiko/hostkeys.py", line 331, in from_line
    key = RSAKey(data=decodebytes(key))
  File "/usr/local/lib/python3.4/dist-packages/paramiko/rsakey.py", line 58, in __init__
    ).public_key(default_backend())
  File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
  File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/__init__.py", line 21, in <listcomp>
    for ep in pkg_resources.iter_entry_points(
AttributeError: 'EntryPoint' object has no attribute 'resolve'
```

**Comment by martinzellner** [comment]
https://github.com/pyca/cryptography/issues/2838 might be related
